### ISSUE TITLE
请问能否发一下这个项目对应的论文的链接吗，想对着论文学习一下

### ISSUE THREAD

**Issue by huang6668** [Biukiii/Trajectory-Planning#1]

**Comment by Harifiri** [comment]
不好意思哈，当时投掉后被reject了，没有见刊哦，因为是之前在公司实习的时候投的，我目前离职了文章可能要等后续公司安排，所以只能看着代码玩了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月24日(周五) 下午3:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Harifiri/Trajectory-Planning] 请问能否发一下这个项目对应的论文的链接吗，想对着论文学习一下 (Issue #1)

**Comment by huang6668** [comment]
没事，感谢分享

**Comment by huang6668** [comment]
再麻烦请问一下为什么我运行这个项目一直卡在33%
